# Generated by Django 3.0.7 on 2021-04-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accused',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_accused', models.CharField(max_length=50)),
                ('photo_accused', models.ImageField(upload_to='photos')),
                ('felony_accused', models.CharField(max_length=50)),
                ('age_accused', models.IntegerField()),
                ('condemnation_accused', models.IntegerField()),
                ('address_accused', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=50)),
                ('photo_employee', models.ImageField(upload_to='photos')),
                ('job_name', models.CharField(max_length=50)),
                ('age_employees', models.IntegerField()),
                ('Salary_employees', models.IntegerField()),
                ('address_employees', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FrontManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('write', models.TextField()),
                ('photo_index', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
